log:
  Level: info

# base config for convert
convert:
  source: "/etc/openclash/rule_provider"
  target: "/etc/mosdns/from_provider"
  processFiles:
    - name: "ai.txt"
      type: "classical"
    - name: "apple.yaml"
      type: "domain"
    - name: "direct.yaml"
      type: "domain"
    - name: "gfw.yaml"
      type: "domain"
    - name: "icloud.yaml"
      type: "domain"
    - name: "proxy.yaml"
      type: "domain"
  enableRegex: True

# run background to watch the file change
service:
  enable: True
  delay: 60
  dbFile: "/etc/mosdns/provider2domainset.db"
